# Generated by Django 2.2.9 on 2020-04-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_displayname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='showdob',
            new_name='showDOB',
        ),
        migrations.AddField(
            model_name='profile',
            name='showPhone',
            field=models.BooleanField(default=False),
        ),
    ]
