# Generated by Django 2.2.9 on 2020-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200422_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='displayImage_url',
            field=models.CharField(default=3, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='displayImage',
            field=models.ImageField(upload_to='displayImage/'),
        ),
    ]
