# Generated by Django 2.2.9 on 2020-04-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200422_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='displayImage_url',
        ),
    ]
