# Generated by Django 2.2.9 on 2020-04-22 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_profile_displayimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='displayImage_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
