# Generated by Django 2.2.9 on 2020-04-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile_displayimage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='displayImage',
        ),
    ]
