# Generated by Django 2.2.3 on 2020-04-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='displayImage_url',
        ),
    ]
