# Generated by Django 2.2.3 on 2020-04-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_profile_displayimage_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('url', models.SlugField(help_text='Link of the Page error occured copy the link from your browser address bar')),
                ('description', models.TextField()),
            ],
        ),
    ]
