# Generated by Django 2.2.3 on 2020-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='displayImage_url',
            field=models.CharField(default='http://localhost:8000/static/img/favicon.png', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bug',
            name='url',
            field=models.SlugField(help_text='Link of the Page Error occured. Copy the link where the Error Occured from your browser address bar'),
        ),
    ]
