# Generated by Django 2.2.3 on 2020-04-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200428_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='displayImage_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
