# Generated by Django 2.2.3 on 2020-04-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200428_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='url',
            field=models.CharField(help_text='Link of the Page Error occured. Copy the link where the Error Occured from your browser address bar', max_length=500),
        ),
    ]
