# Generated by Django 2.2.9 on 2020-04-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('Top Priority', 'danger'), ('Middle Priority', 'warning'), ('Minor Priority', 'success'), ('Other', 'dark')], max_length=100)),
                ('duration', models.IntegerField()),
                ('dontDisplay', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
