# Generated by Django 3.0.6 on 2020-06-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('danger', 'Top Priority'), ('warning', 'Middle Priority'), ('success', 'Minor Priority'), ('dark', 'Other')], max_length=100)),
                ('duration', models.IntegerField()),
                ('dontDisplay', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
