# Generated by Django 2.2.9 on 2020-04-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('danger', 'Top Priority'), ('warning', 'Middle Priority'), ('success', 'Minor Priority'), ('dark', 'Other')], max_length=100),
        ),
    ]
