# Generated by Django 3.0.6 on 2020-06-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('agric', 'agric'), ('biology', 'biology'), ('civic', 'civic'), ('english', 'english'), ('math', 'math'), ('ccp', 'ccp'), ('dp', 'dp'), ('economics', 'economics'), ('ict', 'ict'), ('accts', 'accts'), ('chemistry', 'chemistry'), ('commerce', 'commerce'), ('fisheries', 'fisheries'), ('f-math', 'f-math'), ('f-nut', 'f-nut'), ('government', 'government'), ('literature', 'literature'), ('physics', 'physics')], max_length=100)),
                ('content', models.TextField(default='Download the Material below')),
                ('topic', models.CharField(max_length=100)),
                ('material', models.FileField(blank=True, null=True, upload_to='class-material/')),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
