# Generated by Django 2.2.9 on 2020-04-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('Agric', 'Agric'), ('Biology', 'Biology'), ('Civic', 'Civic'), ('English', 'English'), ('Math', 'Math'), ('CCP', 'CCP'), ('DP', 'DP'), ('Economics', 'Economics'), ('ICT', 'ICT'), ('Accts', 'Accts'), ('Chemistry', 'Chemistry'), ('Commerce', 'Commerce'), ('Fisheries', 'Fisheries'), ('F/math', 'F/math'), ('F/Nut', 'F/Nut'), ('Government', 'Government'), ('Literature', 'Literature'), ('Physics', 'Physics')], max_length=100)),
                ('content', models.TextField(default='Download the Material below')),
                ('topic', models.CharField(max_length=100)),
                ('material', models.FileField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
