# Generated by Django 2.2.9 on 2020-04-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_auto_20200423_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='material',
            field=models.FileField(upload_to='class-material/'),
        ),
    ]
