# Generated by Django 3.0.6 on 2020-06-16 02:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_auto_20200616_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='material',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='material'),
        ),
    ]
