# Generated by Django 2.2.9 on 2020-04-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_auto_20200423_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='material',
            field=models.FileField(null=True, upload_to='class-material/'),
        ),
    ]
