# Generated by Django 2.2.9 on 2020-04-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_auto_20200425_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='class-material/'),
        ),
    ]
